### ISSUE TITLE
Use conditionals in code instead of different code on different branches.

### ISSUE THREAD

**Issue by KristofferC** [JuliaTesting/TestEnv.jl#34] opened 2021-11-23 08:55 UTC
I don't really understand at all what is going on with the code structure here :P.

Why is it not structured like:

```
module TestEnv

if VERSION < v"1.1"
    include("testenv_1.0.jl")
elseif VERSION < v"1.2"
   ...
en

end
```

and have the files like normal in a repo?

As it is right now, it is pretty much impossible to get a view of what different codes there are and how they differ between versions.

**Comment by oxinabox** [comment] 2021-11-23 13:51
Duplicate of #27 
see answers there

> As it is right now, it is pretty much impossible to get a view of what different codes there are and how they differ between versions.

Use standard git (/github) tools to compare between branches.
It is no more or less easy than comparing between two files.
It's just `git diff` instead of `diff`.
(alt you can use githubs diff tool)

**Closed** 2021-11-23 13:52 UTC
