### ISSUE TITLE
How to use with CI?

### ISSUE THREAD

**Issue by ufechner7** [JuliaTesting/TestEnv.jl#46] opened 2022-05-29 09:57 UTC
All my packages that have TestEnv as dependency fail with PkgEval, for example: [![pkgeval](https://juliahub.com/docs/KiteModels/pkgeval.svg)](https://juliahub.com/ui/Packages/KiteModels/kuWuk)

How can I avoid that?

**Comment by oxinabox** [comment] 2022-05-30 15:26
PkgEval i believe tests julia-nightly?
Which makes this a duplicate of https://github.com/JuliaTesting/TestEnv.jl/issues/37#issuecomment-982144597 I believe.
So we can continue this discussion there.

**Closed by oxinabox** 2022-05-30 15:26 UTC
